name: 'setup-vcpkg'
description: 'Setup vcpkg with VCPKG_ROOT, VCPKG_DEFAULT_TRIPLET, asset caching and binary caching.'
branding:
  icon: 'package'
  color: 'yellow'
inputs:
  VCPKG_ROOT:
    description: 'VCPKG_ROOT'
    required: false
    default: ''
  VCPKG_DEFAULT_TRIPLET:
    description: 'VCPKG_DEFAULT_TRIPLET'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'