name: 'setup-vcpkg'
description: 'Setup vcpkg with asset caching, binary caching ...'
branding:
  icon: 'package'
  color: 'red'
inputs:
  VCPKG_DEFAULT_TRIPLET:
    description: 'VCPKG_DEFAULT_TRIPLET'
    required: false
    default: ''
runs:
  using: 'node20'
  main: 'dist/main/index.js'
  post: 'dist/post/index.js'